services:
  - type: web
    name: bests-ia
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install
      playwright install-deps
    startCommand: "gunicorn --worker-class eventlet -w 1 main:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
